import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Database, FilePlus2, MessageSquareText } from 'lucide-react'
import { requireAdmin } from '@/lib/editorial-auth'
import { getEditorialSection, formatEditorialDate } from '@/lib/editorial-data'

const labels: Record<string, [string, string]> = { news: ['Newsroom', 'Manage drafts, published stories and scheduled articles.'], categories: ['Categories', 'Manage the publication taxonomy used across the newsroom.'], events: ['Events', 'Manage upcoming and completed community events.'], submissions: ['Story submissions', 'Review potential stories sent by the FUTO community.'], media: ['Media library', 'Review hosted images and videos.'], admins: ['Administrators', 'Manage editorial access and team roles.'], settings: ['Site settings', 'Manage publication details and configurable contact information.'] }

export default async function EditorialSectionPage({ params }: { params: Promise<{ section: string }> }) {
  await requireAdmin()
  const { section } = await params
  const [title, description] = labels[section] ?? ['Editorial workspace', 'This editorial section is ready for database-backed content.']
  const rows = await getEditorialSection(section)
  const isSubmissions = section === 'submissions'
  return <main className="editorial-main standalone-editor"><Link className="text-link" href="/editorial"><ArrowLeft size={16} data-icon="inline-start" />Back to dashboard</Link><header className="editorial-topbar section-topbar"><div><p className="eyebrow">FUTO CENTRAL / CMS</p><h1>{title}</h1><p className="muted">{description}</p></div><div className="section-actions">{isSubmissions && <Link className="button button-outline" href="/editorial"><MessageSquareText size={16} data-icon="inline-start" />Dashboard</Link>}{section === 'news' && <Link className="button button-gold" href="/editorial/news/new"><FilePlus2 size={16} data-icon="inline-start" />Create post</Link>}</div></header><section className="editorial-panel editorial-table"><div className="panel-heading"><div><p className="eyebrow">DATABASE VIEW</p><h2>Live records</h2></div><span className="status-pill">{rows.length} records</span></div>{rows.length ? <div className="editorial-list">{rows.map((row: Record<string, unknown>) => { const id = String(row.id ?? row.key ?? 'record'); const label = String(row.title ?? row.name ?? row.email ?? row.key ?? row.public_id ?? 'Record'); const status = String(row.status ?? (row.created_at ? formatEditorialDate(String(row.created_at)) : 'Active')); return <Link href={section === 'news' ? `/editorial/news/${id}` : `/editorial/${section}`} className="editorial-list-row" key={id}><span><b>{label}</b><small>{row.created_at ? formatEditorialDate(String(row.created_at)) : 'Editorial record'}</small></span><span className={`editorial-badge ${status}`}>{status}</span><ArrowUpRight size={15} /></Link> })}</div> : <div className="empty-editorial"><Database size={30}/><strong>No records yet</strong><p>This workspace is connected to Neon and will display new records here.</p>{section === 'news' && <Link className="text-link" href="/editorial/news/new">Create the first post <ArrowUpRight size={14} /></Link>}</div>}</section></main>
}
