CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS admins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, name text, role text NOT NULL DEFAULT 'admin' CHECK (role IN ('admin','super_admin')), password_hash text, is_active boolean NOT NULL DEFAULT true, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL, role text NOT NULL DEFAULT 'admin' CHECK (role IN ('admin','super_admin')), token_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz, invited_by uuid REFERENCES admins(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), admin_id uuid NOT NULL REFERENCES admins(id) ON DELETE CASCADE, token_hash text UNIQUE NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, slug text UNIQUE NOT NULL, description text, image_url text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS authors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, bio text, image_url text, email text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS articles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, slug text UNIQUE NOT NULL, excerpt text NOT NULL, content text NOT NULL, category_id uuid REFERENCES categories(id), author_id uuid REFERENCES authors(id), featured_image text, featured_image_alt text, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','scheduled','archived')), published_at timestamptz, scheduled_for timestamptz, reading_time integer NOT NULL DEFAULT 4 CHECK (reading_time > 0), seo_title text, meta_description text, is_featured boolean NOT NULL DEFAULT false, views integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL, slug text UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS article_tags (article_id uuid REFERENCES articles(id) ON DELETE CASCADE, tag_id uuid REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(article_id, tag_id));
CREATE TABLE IF NOT EXISTS events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, slug text UNIQUE NOT NULL, description text NOT NULL, category text NOT NULL, starts_at timestamptz NOT NULL, ends_at timestamptz, location text, organizer text, image_url text, image_alt text, registration_url text, status text NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming','ongoing','completed','cancelled')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), public_id text UNIQUE NOT NULL, secure_url text NOT NULL, resource_type text NOT NULL CHECK (resource_type IN ('image','video','raw')), format text, width integer, height integer, duration numeric, uploaded_by uuid REFERENCES admins(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS story_submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), full_name text NOT NULL, email text NOT NULL, phone text, relationship_to_futo text, title text NOT NULL, category text NOT NULL, summary text NOT NULL, content text NOT NULL, location text, event_date date, media jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','under_review','approved','rejected','published')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS site_settings (key text PRIMARY KEY, value jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS articles_status_published_idx ON articles(status, published_at DESC);
CREATE INDEX IF NOT EXISTS articles_category_idx ON articles(category_id);
CREATE INDEX IF NOT EXISTS events_starts_idx ON events(starts_at);
CREATE INDEX IF NOT EXISTS submissions_status_idx ON story_submissions(status, created_at DESC);
INSERT INTO categories (name, slug, description) VALUES ('Campus News','campus-news','Updates and developments across the FUTO community.'),('Academics','academics','Research, learning and academic achievement.'),('Student Life','student-life','The people, clubs and experiences shaping campus life.'),('Events','events','Programs, gatherings and activities.'),('Sports','sports','Competition and sporting life at FUTO.'),('Technology & Innovation','technology-innovation','Practical ideas, research and innovation.'),('Opportunities','opportunities','Scholarships, internships and useful pathways.'),('Community','community','Stories about shared progress and community.') ON CONFLICT (slug) DO NOTHING;
INSERT INTO site_settings (key, value) VALUES ('publication', '{"name":"FUTO Central","contactEmail":"hello@futocentral.name.ng"}'::jsonb) ON CONFLICT (key) DO NOTHING;
-- The super-admin email is seeded without a credential. Generate an Argon2id hash server-side before inserting password_hash.
INSERT INTO admins (email, name, role) VALUES ('wisdommeremeze@gmail.com','Super Administrator','super_admin') ON CONFLICT (email) DO NOTHING;

-- Public demo content remains in components/futo/data.ts until DATABASE_URL is configured and content migration is run.
-- No plaintext password or credential is included in this file.
