'use client'

import { useState } from 'react'
import { ArrowUpRight, BookOpen, Check, ChevronRight, Compass, Heart, Lightbulb, Menu, Search, ShieldCheck, Users, X } from 'lucide-react'

const navItems = ['Home', 'News', 'Academics', 'Campus Life', 'Events', 'Sports', 'Opportunities']
const coverage = [
  ['Campus News', 'Important developments, announcements and stories from around FUTO.', BookOpen],
  ['Academics', 'Academic developments, research, faculty achievements and educational updates.', Lightbulb],
  ['Student Life', 'The experiences, activities and communities that shape student life at FUTO.', Users],
  ['Events', 'Campus events, conferences, competitions, programs and activities.', Compass],
  ['Technology & Innovation', 'Engineering, technology, research, inventions, projects and ideas.', Lightbulb],
  ['Sports', 'Sports news, competitions, teams, athletes and achievements.', Heart],
  ['Opportunities', 'Scholarships, internships, fellowships, competitions, grants and more.', Check],
  ['Community', 'Stories involving alumni, staff, students and the wider FUTO community.', Users],
] as const
const values = [
  ['Accuracy', 'We strive to present information carefully and distinguish confirmed information from developing stories.'],
  ['Responsibility', 'We understand that published information can affect real people and communities.'],
  ['Relevance', 'We focus on stories and information that matter to the FUTO community.'],
  ['Transparency', 'We aim to be clear about our platform, editorial approach and how information is presented.'],
  ['Community', 'FUTO Central exists to serve the wider FUTO community and highlight the people who make it what it is.'],
  ['Innovation', 'As a technology-focused university community, we embrace digital tools and new ways of sharing information.'],
]
const principles = [
  ['Verify before publishing', 'Where possible, information should be checked against reliable sources before publication.'],
  ['Provide context', 'Readers should receive enough context to understand why a development matters.'],
  ['Correct mistakes', 'If an error is identified, FUTO Central should be willing to correct it transparently.'],
  ['Avoid misleading headlines', 'Headlines should attract attention without deliberately misleading readers.'],
  ['Respect people', 'Coverage should consider the dignity and privacy of students, staff and community members.'],
]

function Header({ onSearch }: { onSearch: () => void }) {
  const [open, setOpen] = useState(false)
  return <><header className="site-header"><div className="header-inner"><a href="/" className="wordmark"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/android-chrome-192x192-0XMwKOjm2ruwu2rdmQ74wiatKXHlrL.png" alt="" /><span>FUTO <b>Central</b></span></a><nav className="desktop-nav" aria-label="Primary navigation">{navItems.map((item) => <a href={item === 'Home' ? '/' : item === 'News' ? '/news' : item === 'Academics' ? '/news?category=Academics' : item === 'Campus Life' ? '/news?category=Student%20Life' : item === 'Events' ? '/news?category=Events' : item === 'Sports' ? '/news?category=Sports' : '/news?category=Opportunities'} key={item}>{item}</a>)}<a className="active" href="/about">About</a></nav><div className="header-actions"><button className="icon-button" onClick={onSearch} aria-label="Open search"><Search size={19} /></button><a className="submit-button" href="/submit-story">Submit a Story <ArrowUpRight size={15} /></a><button className="menu-button" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div></div></header>{open && <div className="mobile-menu"><nav aria-label="Mobile navigation">{[...navItems, 'About'].map(item => <a key={item} href={item === 'Home' ? '/' : item === 'About' ? '/about' : `/#${item.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setOpen(false)}>{item}<ArrowUpRight size={16} /></a>)}</nav></div>}</>
}
function SearchOverlay({ close }: { close: () => void }) { return <div className="search-overlay" role="dialog" aria-modal="true" aria-label="Search FUTO Central"><button className="close-search" onClick={close} aria-label="Close search"><X /></button><div className="search-inner"><span className="eyebrow">FUTO CENTRAL SEARCH</span><h2>Find a story worth reading.</h2><div className="search-field"><Search size={20} /><input autoFocus aria-label="Search news, stories, events" placeholder="Search news, stories, events..." /></div></div></div> }
function Footer() { return <footer className="site-footer"><div className="container footer-main"><div className="footer-brand"><a href="/" className="wordmark light"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/android-chrome-192x192-0XMwKOjm2ruwu2rdmQ74wiatKXHlrL.png" alt="" /><span>FUTO <b>Central</b></span></a><p>Independent news and information for the FUTO community.</p><div className="socials"><a href="/about" aria-label="Facebook">f</a><a href="/about" aria-label="X">𝕏</a><a href="/about" aria-label="Instagram">ig</a><a href="/about" aria-label="WhatsApp">wa</a><a href="/about" aria-label="YouTube">yt</a></div></div><div className="footer-links"><div><h3>Explore</h3>{['Home','News','Academics','Campus Life','Events','Sports','Opportunities'].map(x => <a href={x === 'Home' ? '/' : `/#${x.toLowerCase().replaceAll(' ', '-')}`} key={x}>{x}</a>)}</div><div><h3>About</h3>{['About FUTO Central','Our Mission','Editorial Approach','Contact','Submit a Story'].map(x => <a href={x === 'About FUTO Central' ? '/about' : x === 'Contact' ? '/contact' : x === 'Submit a Story' ? '/submit-story' : '/about'} key={x}>{x}</a>)}</div><div><h3>Legal</h3><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Use</a><a href="/editorial-policy">Editorial Policy</a></div></div></div><div className="container footer-bottom"><span>© 2026 FUTO Central. All rights reserved.</span><span>Independent publishing for the FUTO community.</span></div></footer> }
function Eyebrow({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span> }
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="section-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{text && <p>{text}</p>}</div></div> }

export default function AboutPage() {
  const [search, setSearch] = useState(false)
  return <div className="futo-site about-page"><Header onSearch={() => setSearch(true)} />{search && <SearchOverlay close={() => setSearch(false)} />}<main>
    <section className="about-hero container"><div><Eyebrow>About FUTO Central</Eyebrow><h1>Connecting the FUTO community through news, stories and information</h1><p>FUTO Central is a digital news and information platform created to keep the Federal University of Technology, Owerri community informed about the people, events, achievements, opportunities and developments shaping life at FUTO.</p><a className="dark-link" href="#story">Our story <ArrowUpRight size={17} /></a></div><div className="about-hero-art"><div className="placeholder-mark"><span>FUTO</span><strong>Central</strong><small>Stories from our campus</small></div></div></section>
    <section id="story" className="about-story container"><Heading eyebrow="Our story" title="A clearer way to discover what is happening at FUTO" /><div className="story-text"><p>Universities are always changing. New ideas emerge in classrooms and laboratories, communities form around shared interests, and important updates can move quickly from one part of campus to another.</p><p>FUTO Central was created with a simple vision: bring relevant FUTO stories together in one accessible digital place for students, staff, alumni and everyone connected to the university community.</p><p>We are an independent platform. We do not speak for FUTO or its administration; we aim to make useful information easier to find, understand and share.</p></div></section>
    <section className="why-section"><div className="container why-grid"><div><Eyebrow>Why FUTO Central?</Eyebrow><h2>There is always a story happening at FUTO.</h2></div><div><p className="lead">Those stories can come from classrooms, laboratories, departments, student organizations, sporting activities, events, research, innovation and community life.</p><div className="reason-list">{[['Discover','Find important developments and stories from around FUTO.'],['Stay informed','Keep up with news, announcements, opportunities and events.'],['Celebrate','Highlight the achievements, creativity and innovation of the community.'],['Connect','Create a digital space where relevant information can be discovered and shared.']].map(([a,b]) => <div key={a}><strong>{a}</strong><p>{b}</p></div>)}</div></div></div></section>
    <section className="editorial-section container"><Heading eyebrow="What we cover" title="The people, ideas and moments that make up FUTO" text="Our coverage is shaped by what is useful, relevant and meaningful to the wider FUTO community." /><div className="coverage-grid">{coverage.map(([title,text,Icon]) => <article className="coverage-card" key={title}><Icon size={21} /><h3>{title}</h3><p>{text}</p><ArrowUpRight size={16} /></article>)}</div></section>
    <section className="mission-vision"><div className="container mv-grid"><div><Eyebrow>Our mission</Eyebrow><h2>To make relevant FUTO news, information and stories easier to discover, understand and share.</h2><p>We want useful information to feel accessible, responsible and connected to the people it serves. Through technology and thoughtful publishing, FUTO Central can help give visibility to achievements and everyday stories that deserve attention.</p></div><div className="vision-panel"><Eyebrow>Our vision</Eyebrow><h2>To build a trusted digital destination for discovering the stories that matter to the FUTO community.</h2><p>Our future direction is a reliable source of information, a place for opportunities and achievements, and a living digital archive of important campus stories.</p></div></div></section>
    <section className="editorial-section container"><Heading eyebrow="What we stand for" title="Values that guide the platform" /><div className="values-grid">{values.map(([title,text]) => <article key={title}><span className="value-line" /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="founder-section"><div className="container founder-grid"><div className="founder-placeholder"><span>Founder photo</span><small>Coming soon</small></div><div className="founder-copy"><Eyebrow>Meet the founder</Eyebrow><h2>Meze</h2><p className="role">Founder & Developer, FUTO Central</p><p>FUTO Central was founded and developed by Meze with the goal of creating a modern digital platform dedicated to the FUTO community. The platform combines an interest in technology, digital publishing and the people who make FUTO what it is.</p><p className="editable-note">Founder biography can be expanded here as new information is added.</p><a className="text-link" href="#contact">Get in touch <ArrowUpRight size={16} /></a></div></div></section>
    <section className="personal-section container"><Eyebrow>Why I built FUTO Central</Eyebrow><div className="personal-grid"><h2>I wanted to build a platform where members of the FUTO community could easily discover what is happening around the university.</h2><div><p>FUTO is filled with people, ideas, achievements and stories worth knowing. This platform is my attempt to create a useful digital space where those stories can be found and shared.</p><div className="quote">“FUTO Central is a digital space for the stories that deserve to be discovered.”<small>Meze · Founder & Developer</small></div></div></div></section>
    <section className="approach-section"><div className="container approach-grid"><div><Eyebrow>How we approach information</Eyebrow><h2>Thoughtful publishing starts with respect for the reader.</h2></div><div className="principles">{principles.map(([title,text],i) => <div key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
    <section className="independence container"><Eyebrow>Our independence</Eyebrow><h2>FUTO Central is an independent digital news and information platform.</h2><p>Unless explicitly stated otherwise, publication on FUTO Central should not be interpreted as an official communication from FUTO or its administration.</p></section>
    <section id="contact" className="contact-cta container"><div><Eyebrow>Have a story to share?</Eyebrow><h2>Let&apos;s keep FUTO connected.</h2><p>Have a question, correction, story idea or information you&apos;d like FUTO Central to know about? Get in touch with us.</p></div><div className="cta-actions"><a className="dark-link" href="/contact">Contact FUTO Central <ArrowUpRight size={17} /></a><a className="outline-link" href="/submit-story">Submit a Story <ArrowUpRight size={17} /></a></div></section>
  </main><Footer /></div>
}
