'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowUpRight, CalendarDays, CheckCircle2, ChevronRight, FilePlus2, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, Tags, Upload, Users, X } from 'lucide-react'
import type { EditorialOverview } from '@/lib/editorial-data'

const items = [['Dashboard', '/editorial', LayoutDashboard], ['News', '/editorial/news', FilePlus2], ['Create Post', '/editorial/news/new', FilePlus2], ['Categories', '/editorial/categories', Tags], ['Events', '/editorial/events', CalendarDays], ['Submissions', '/editorial/submissions', FilePlus2], ['Media', '/editorial/media', Upload], ['Admins', '/editorial/admins', Users], ['Settings', '/editorial/settings', Settings]] as const
const stats = (overview: EditorialOverview) => [['Articles', overview.articles, '/editorial/news', 'Total newsroom content'], ['Published', overview.published, '/editorial/news?status=published', 'Live on the public site'], ['Drafts', overview.drafts, '/editorial/news?status=draft', 'Ready for your attention'], ['Submissions', overview.submissions, '/editorial/submissions', 'Awaiting review']] as const

export function EditorialDashboard({ overview }: { overview: EditorialOverview }) {
  const [open, setOpen] = useState(false)
  return <div className="editorial-shell">
    <aside className={open ? 'editorial-sidebar is-open' : 'editorial-sidebar'}>
      <div className="editorial-brand"><ShieldCheck size={20} /><span>FUTO Central</span><button className="editorial-close" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <p className="editorial-kicker">Editorial Dashboard</p>
      <nav className="editorial-nav" aria-label="Editorial navigation">{items.map(([label, href, Icon]) => <Link href={href} key={label} onClick={() => setOpen(false)} className={label === 'Dashboard' ? 'active' : ''}><Icon size={17} />{label}</Link>)}</nav>
      <div className="editorial-sidebar-bottom"><Link href="/"><ArrowLeft size={16} />View public site</Link><form action="/api/editorial/logout" method="post"><button type="submit"><LogOut size={16} />Log out</button></form></div>
    </aside>
    {open && <button className="editorial-overlay" onClick={() => setOpen(false)} aria-label="Close navigation" />}
    <main className="editorial-main"><header className="editorial-topbar"><button className="editorial-menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><div><p className="eyebrow">FUTO CENTRAL / CMS</p><h1>Good morning, editor</h1><p className="editorial-subtitle">Here&apos;s what&apos;s happening across your newsroom today.</p></div><Link className="button button-gold" href="/editorial/news/new"><FilePlus2 size={16} />Create post</Link></header>
      <section className="editorial-notice"><div className="notice-icon"><CheckCircle2 size={17} /></div><div><strong>Editorial system operational</strong><p>Live content, submissions and publishing workflows are synced with Neon.</p></div><span className="status-pill">Connected</span></section>
      <section className="editorial-stats" aria-label="Editorial overview">{stats(overview).map(([label, value, href, caption]) => <Link href={href} className="editorial-stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>{caption}</small><ArrowUpRight className="stat-arrow" size={16} /></Link>)}</section>
      <section className="editorial-grid"><article className="editorial-panel"><div className="panel-heading"><div><p className="eyebrow">CONTENT WORKFLOW</p><h2>Recent articles</h2></div><Link href="/editorial/news">View all <ArrowUpRight size={14} /></Link></div>{overview.recentArticles.length ? <div className="editorial-list">{overview.recentArticles.map((article) => <Link href={`/editorial/news?article=${article.id}`} className="editorial-list-row" key={article.id}><span><b>{article.title}</b><small>Created {new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium' }).format(new Date(article.created_at))}</small></span><span className={`editorial-badge ${article.status}`}>{article.status}</span><ChevronRight size={16} /></Link>)}</div> : <div className="empty-editorial"><FilePlus2 size={26} /><strong>No articles yet</strong><p>Create the first draft for the newsroom.</p><Link className="text-link" href="/editorial/news/new">Create a draft <ArrowUpRight size={14} /></Link></div>}</article><article className="editorial-panel submission-panel"><div className="panel-heading"><div><p className="eyebrow">COMMUNITY DESK</p><h2>Story submissions</h2></div><Link href="/editorial/submissions">View all <ArrowUpRight size={14} /></Link></div><div className="submission-callout"><div className="submission-number">{overview.submissions}</div><div><strong>{overview.submissions ? 'Stories need review' : 'All caught up'}</strong><p>{overview.submissions ? 'Review incoming community stories and decide what belongs in the newsroom.' : 'There are no pending submissions in your review queue.'}</p><Link className="text-link" href="/editorial/submissions">Open review queue <ArrowUpRight size={14} /></Link></div></div></article></section>
      <section className="quick-actions"><div><p className="eyebrow">EDITORIAL TOOLKIT</p><h2>Keep the newsroom moving</h2></div><div className="quick-action-list"><Link href="/editorial/news/new"><FilePlus2 size={18} /><span><b>Write a new story</b><small>Start a draft from scratch</small></span><ChevronRight size={16} /></Link><Link href="/editorial/media"><Upload size={18} /><span><b>Browse media library</b><small>Find images for your next story</small></span><ChevronRight size={16} /></Link><Link href="/editorial/settings"><Settings size={18} /><span><b>Update site settings</b><small>Manage publication details</small></span><ChevronRight size={16} /></Link></div></section>
    </main>
  </div>
}

export function EditorialLogin() { return <main className="editorial-login"><div className="login-card"><div className="editorial-brand"><ShieldCheck size={22} /><span>FUTO Central</span></div><p className="eyebrow">EDITORIAL DASHBOARD</p><h1>Sign in to your desk</h1><p className="muted">Secure access for the FUTO Central editorial team.</p><form action="/api/editorial/login" method="post" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); fetch('/api/editorial/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }).then(async (response) => { if (response.ok) window.location.href = '/editorial'; else alert('Invalid credentials') }).catch(() => alert('Unable to sign in')) }}><label htmlFor="email">Email<input id="email" name="email" type="email" required autoComplete="email" /></label><label htmlFor="password">Password<input id="password" name="password" type="password" required autoComplete="current-password" /></label><button className="button button-green" type="submit">Sign in</button></form><Link className="muted text-link" href="/">Return to public site</Link></div></main> }
